# iOS CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/ios-migrating-from-1-2/ for more details
#
version: 2
jobs:

  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-27-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Download Dependencies
          command: bash gradlew androidDependencies
      - run:
          name: build the whole project
          command: bash gradlew build -x test

  unittest:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-27-alpha
    resource_class: large
    environment:
      JVM_OPTS: -Xmx3200m

    steps:
      - checkout

      - run:
          name: run unit tests
          command: |
            python3 CircleciScripts/run_unittest.py test_results
      - run:
          name : check unit test result 
          command : bash CircleciScripts/check_test_result.sh test_results
          
      - store_artifacts:
          path: test_results

  release_maven:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-27-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    resource_class: large
 
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "build.gradle" }}

      - run:
          name: install aws cli
          command: |
            sudo pip install awscli
      - run:
          name: install android build tools
          command: |
            echo "${HOME}"
            echo "$JAVA_HOME"
            echo "$ANDROID_HOME"
            echo "$PATH"          
            ls  "$ANDROID_HOME"
            ls  "$ANDROID_HOME/platforms/android-27"            
            echo 'export ANDROID_PLATFORM="$ANDROID_HOME/platforms/android-27"' >> $BASH_ENV
            sdkmanager "platforms;android-27" "build-tools;27.0.3" "extras;google;m2repository" "extras;android;m2repository"          
                 
      - run:
          name: download gpghome
          command: |
            aws s3 cp s3://gpghome-csun/gpghome.zip gpghome.zip
            unzip -a gpghome.zip
            echo "gpghome contents:"
            ls gpghome

      - run:
         name: install maven
         command: |
          sudo apt-get install maven
      - run:
          name: Download Dependencies
          command: bash gradlew androidDependencies

      - run:
          name: publish to maven
          command: |
            echo "${HOME}"
            echo "$JAVA_HOME"
            echo "$ANDROID_HOME"
            echo "$M2_HOME"
            bash CircleciScripts/maven-release.sh



workflows:
  version: 2
  build_and_test:
    jobs: 
      - build:
          filters:
            branches:
              ignore: /.*/
      - unittest:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/

  release_sdk:
    jobs: 
      - build:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^[0-9]+.[0-9]+.[0-9]+$/

      - unittest:
          requires:
            - build

      - release_maven    

        
